export default {
  APP_HANDLE_ANALYTICS: 'APP_HANDLE_ANALYTICS',
  APP_LOADING_ANALYTICS: 'APP_LOADING_ANALYTICS',
  APP_SET_ANALYTICS: 'APP_SET_ANALYTICS',
  APP_SET_SESSION: 'APP_SET_SESSION',
  APP_HANDLE_USERS: 'APP_HANDLE_USERS',
  APP_SET_USERS: 'APP_SET_USERS',
};
